language: scala
jdk:
  - oraclejdk7
after_success:
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - "mvn deploy --settings target/travis/settings.xml"

branches:
  except:
    - travis

env:
  global:
    - secure: "FH0wNH0J4AcY1xE6Vo22gmFkYKZ7HXbIt4PyHAKGaRpkMUJe9Or08kgTvaVj\nCIZxjBEawd0jbufLj9A8948plbJnwruZw5fCsbL6JEsFo8P9QZ1S1OFdo/Oy\nm0BaX5fpTCj/0pX3tbtWTpfUYah6aZlZb3H6/ijLjY00Lehltdg="
    - secure: "d7FlocerxCkX5f5lakh09O2Rol8Ph1FH4gfQ+FTUhOXAWp/5+e4cJmkiJy7+\n7tme49Nyx4wDUiuoU+bta96GV3CovCl2jlTc3p11rR0rc4BtwlTNQIphXwal\nxsVntkvOvta/IdyEGOui3/T2Cf/wQ7jVVnZldAUmYspsGWg1C54="
